services:
  server:
    build: .
    networks:
      - traefik-proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.pizza.rule=Host(`pizza.dk-gl.eu`)
      - traefik.http.routers.pizza.entrypoints=https
      - traefik.http.services.pizza-backend.loadbalancer.server.port=80
networks:
  traefik-proxy:
    external: true
    name: traefik-proxy
